# Generated by Django 3.2.7 on 2021-10-04 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasnim_main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('تاریخ', django_jalali.db.models.jDateField(auto_created=True)),
                ('حساب_خیر', models.TextField(max_length=16)),
                ('نام_خیر', models.TextField(max_length=100)),
                ('مبلغ', models.DecimalField(decimal_places=2, max_digits=30)),
                ('نام_ورودی', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_joined', models.DateTimeField(auto_created=True)),
                ('address', models.TextField(max_length=200)),
                ('zip_code', models.TextField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('تاریخ', django_jalali.db.models.jDateField(auto_created=True)),
                ('حساب_مقصد', models.TextField(max_length=16)),
                ('نام_ورودی', models.TextField(max_length=300)),
                ('مبلغ', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('تاریخ', django_jalali.db.models.jDateField(auto_created=True)),
                ('نام_پروژه', models.CharField(max_length=30)),
                ('توضیحات', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='shopping_list',
        ),
        migrations.RemoveField(
            model_name='subcat',
            name='Good',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shopping_cart',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Subcategories',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='Subcat',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='output',
            name='related_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='پروژه_مربوطه', to='tasnim_main_app.project', verbose_name='پروژه مربوطه'),
        ),
    ]
