# Generated by Django 3.2.7 on 2021-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasnim_main_app', '0002_auto_20211004_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='مبلغ',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
    ]
