# Generated by Django 3.2.7 on 2021-10-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasnim_main_app', '0003_alter_input_مبلغ'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='input_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_proj', to='tasnim_main_app.project', verbose_name='پروژه'),
        ),
    ]
