# Generated by Django 3.2.7 on 2021-10-07 17:20

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasnim_main_app', '0004_input_input_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='نام_ورودی',
            field=models.TextField(max_length=300, verbose_name='یاد نشان'),
        ),
        migrations.AlterField(
            model_name='output',
            name='تاریخ',
            field=django_jalali.db.models.jDateField(auto_created=True, default='0'),
        ),
    ]
